#!/usr/bin/env bash
# This is a bash script to transfer files from local machine to remote machine
# using SSH connection started with with scp command wich also perform file transfer
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
# $0: The name of the script itself.
# $1, $2, $3, ...: The positional parameters representing the arguments passed to the script.
# $1 corresponds to the first argument, $2 to the second, and so on.
#  $#  : The number of arguments passed to the script.
# important : use spaces in square brackets
if [ $# gt 3 ]; then
	scp  $1 "${3}@${2}:~/" -i $4 -o StrictHostKeyChecking=no
	# $3@$2:~/ : stands for username@ip:destination_path_on_remote_machine
else # if less than 4 parameters passed; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
