#!/usr/bin/env bash
# task 1: bash script to Install HAproxy on lb-01 server
# then configure it to roundrobin load bancer algorithm
# for other 2 web servers 376213-web-01	, 376213-web-02
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
'
backend AHesham-backend
        balance roundrobin
        server 376213-web-01 54.165.176.205:80 check
        server 376213-web-02 52.204.94.151:80 check
frontend AHesham-frontend
        bind *:80
        mode http
        default_backend AHesham-backend
'
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
# this also could be done using next line don't forget >> to append
#echo "$config" >> /etc/haproxy/haproxy.cfgecho

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
