#!/usr/bin/env bash
# take argument string (IP), then send to ping with specific output  given
# Ping the IP 5 times
if [ -z "$1" ] #$1 input's first argument
then #no argument given (no input from user)
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1" #ping the IP 5 times
fi #task 5
# A. Hesham
# In a bash script, you can access the arguments passed to the script using special variables.
#The arguments are stored in variables named $1, $2, $3, and so on, till $9
#where $1 represents the first argument, $2 the second argument, and so on. You can access up to 9 arguments this way.
