#!/usr/bin/env bash
# task 0 : a Bash script to fix Nginx config. that fail to listen on port 80.
# see readme file for more details

# Problem to fix 
# root@966caff:/# curl 0:80
# curl: (7) Failed to connect to 0 port 80: Connection refused

# solution :
# conflict due to /etc/nginx/sites-enabled have another conflicting config file , Because this config
# file isn't a symbol link (isn't sym linked) to the default config inside /etc/nginx/sites-available/default
# do this symbol link using  (ln -f -s ) and check the config file inside sites-available if any misconfiguration (here there wasn't ),
# then (service nginx restart)

#  useful commands I have used to debug:
#         service nginx status
#         sudo netstat -tuln | grep ':80'
#         nginx -t
#         service nginx restart
#         ln -s -f /path/of/source/file /path/to/destination/directory

# -s to create symbol link
# -f to force creation even if the destination have a file or directory with the same file name
# i.e. it will create this symbol link file to avoid failure, while removing old existing files or dirs that have same name
# never forget "/" at start of every path
sudo ln -s -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled

# restart nginx to apply new config.file
sudo service nginx restart
