#!/usr/bin/env bash
# a file that do some opertions in sequence ,creats , file , append PID  of this script to it on creation
# handle some signals

echo "$$" > /var/run/myscript.pid # create a file that contains this bash script's ID

killfunc(){
	rm /var/run/myscript.pid
	exit
}

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT

# && could be used instead of ";" also
  trap 'echo "I hate the kill command"; killfunc' SIGTERM

# I could call the function here but just trying another way
  trap 'rm /var/run/myscript.pid; exit' SIGQUIT
done
