#!/usr/bin/env bash
# stop "kill" a running process without using kill or killall commands , A. Hesham
pgrep --full "4-to_infinity_and**" | pkill
# here I used pkill command instead
# but first i used pgrep to find the pattern and send it using pipe "|" to pkill
