#!/usr/bin/env bash
# This is a bash script to print "Best School" 10 times :) using while
i=1
while (( "$i" <= 10 )); do echo "Best School"; ((i++)); done
#or the below line
#while [ "$i" -le 10 ]; do echo "Best School"; let i+=1; done
#while [ "$i" -le 10 ]; do echo "Best School"; (( i += 1 )); done
#also those are valid increment (( i+=1 )), (( i = i+1 )) or using let
# see Example 8-2. Using Arithmetic Operations
# https://tldp.org/LDP/abs/html/ops.html
