#!/usr/bin/env bash
# This is a bash script to print "Best School" 10 times :) using while
i=1
while [ "$i" -le 10 ]; do
# important : use spaces in square brackets
if [ "$i" -eq 4 ]; then
	echo "bad luck"
elif [ "$i" -eq 8 ]; then
	echo "good luck"
else
	echo "Best School"	
fi
((i++)); done
# if [ "$i" = 9 ] also does the same
