#!/usr/bin/env bash
# This is a bash script to print "Best School" 20 times :) using while with exceptions
i=1
while [ "$i" -le 20 ]; do echo "$i"
# important : use spaces in square brackets
case "$i" in
4)
	echo "bad luck from China"
	;;
	9)
	echo "bad luck from Japan"
	;;
	17)
	echo "bad luck from Italy"
esac
((i++)); done
