#!/usr/bin/env bash
# Bash script to force Nginx to run with Nginx User, with port 8080
sudo service nginx stop
echo "user nginx;" >> /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
