#!/usr/bin/env bash
# Bash script to force Nginx to run with Nginx User, with port 8080
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
