#!/usr/bin/env bash
# Generate an RSA type SSH key pair with a 4096-bit key length, passphrase
# and save with "school" set as files names. at the "~/.ssh/" directory.
ssh-keygen -t rsa -b 4096 -p "betty" -f "school"
